title: AESF Hoempage
description: [A short description of your site's purpose]

theme: jekyll-theme-modernist


baseurl: "https://nybles.github.io/adam"
url: "https://nybles.github.io/adam"

# Reading Files
include:
  - _pages
  

