title: AESF Hoempage
description: [A short description of your site's purpose]

baseurl: /aesf_homepage
url: https://jazznbass.github.io/aesf_homepage

# Build settings
theme: jekyll-theme-tactile #minima

# theme: jekyll-theme-tactile


plugins:
  - jekyll-feed



markdown: kramdown
permalink: /:year/:title:output_ext

# Reading Files
include:
  - _pages
