title: AESF Hoempage
description: >- # this means to ignore newlines until "baseurl:"
  Arbeitsgemeinschaft Empirischer Sonderpädagogischer Forschung

email: jazznbass98@gmail.com
github_username:  jazznbass

baseurl: /aesf_homepage
url: https://jazznbass.github.io/aesf_homepage

# Build settings
theme: minima

# theme: jekyll-theme-tactile


plugins:
  - jekyll-feed



markdown: kramdown
permalink: /:year/:title:output_ext

# Reading Files
include:
  - _pages
